# Generated by Django 4.1.5 on 2023-01-27 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="patient",
        ),
        migrations.AddField(
            model_name="appointment",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.DeleteModel(
            name="Prescription",
        ),
    ]
