# Generated by Django 4.1.5 on 2023-02-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0002_remove_prescription_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='saveEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('your_email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('messages', models.CharField(max_length=500)),
            ],
        ),
    ]
