# Generated by Django 4.1.5 on 2023-02-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0006_alter_contactenquiry_your_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='your_email',
            field=models.CharField(max_length=100),
        ),
    ]
