# Generated by Django 4.1.6 on 2023-02-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0008_appointment_messages_alter_appointment_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('chestPain', models.IntegerField(blank=True)),
                ('restingBloodPressure', models.IntegerField(blank=True)),
                ('cholesterol', models.IntegerField(blank=True)),
                ('fastingBloodSugar', models.IntegerField(blank=True)),
                ('restingElectrocardiographic', models.IntegerField(blank=True)),
                ('maximumHeartRate', models.IntegerField(blank=True)),
                ('ExerciseInducedAngina', models.IntegerField(blank=True)),
                ('STdepression', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
