# Generated by Django 4.1.6 on 2023-02-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0012_alter_heartdisease_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartdisease',
            name='ExerciseInducedAngina',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='STdepression',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='chestPain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='cholesterol',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='fastingBloodSugar',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='maximumHeartRate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='restingBloodPressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='restingElectrocardiographic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='heartdisease',
            name='sex',
            field=models.IntegerField(null=True),
        ),
    ]
