# Generated by Django 5.2.5 on 2025-11-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0014_diabetessubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='your_email',
            field=models.EmailField(max_length=254),
        ),
    ]
